project_id = "avkukzfvqtjovfrrhzer"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://avkukzfvqtjovfrrhzer.lovable.app"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_change_confirmations = true
enable_phone_confirmations = false
enable_phone_change_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template = {}
smtp = {}

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"
test_otp = {}
max_frequency = "5s"

[edge_runtime]
enabled = true
port = 54330
inspector_port = 54331

[analytics]
enabled = false
port = 54327
vector_port = 54328
gw_port = 54329

[functions.create-payment]
verify_jwt = true

[functions.midtrans-webhook]
verify_jwt = false

[functions.send-premium-email]
verify_jwt = false