// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avkukzfvqtjovfrrhzer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2a3VremZ2cXRqb3ZmcnJoemVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNzQ3MzYsImV4cCI6MjA3MTg1MDczNn0.kCUadLVnlmoYbiWHzQXPOc1Omv10QOSlD2UtWN26Xgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});